### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by nsmith5** [JuliaWeb/GeoIP.jl#20]
It might be good to have an option to query the database without loading the entire thing into ram. Its seems like a waste of time and memory for smaller queries. Using something like SQLite as a data store would be helpful to facilitate this.

**Comment by Arkoniak** [comment]
I have my doubts regarding this issue. SQLite queries will be notoriously slow and I doubt they can be efficiently implemented, taking into account that there exists no convenient key.   At the same time, they require lots of additional machinery, so it is going to be a lot of effort with very insignificant benefit. At the same time, In view of the new refactoring, it may be worthwhile to introduce following types:

```
GeoIPDB{CSV}
GeoIPDB{LazyCSV}
GeoIPDB{Binary}
GeoIPDB{LazyBinary}
```

where `Lazy` versions work via `mmap` and as such introduce minimal overhead. Of course, it may be not possible.

**Comment by Arkoniak** [comment]
As of 0.5.2 memory size of the GeoLite database is less than 300Mb which is rather small by current standards. So I close this issue since I see no practical purpose. If need arises though, it should be implemented differently: instead of storing in SQLite, we should store data in some binary format (a-la JLD2) and load in memory only indices. This way, the memory footprint will be very light, and at the same time, we can extract data just by using `seek` utility.
