### ISSUE TITLE
Package does not seem to work

### ISSUE THREAD

**Issue by fredrikekre** [JuliaWeb/GeoIP.jl#47]
Not sure what I am missing:

```julia
julia> using GeoIP, Sockets

julia> a = ip"1.2.3.4";

julia> geolocate(a)
[ Info: Geolocation data not in memory. Loading...
┌ Error: Geolocation data cannot be read. Data directory may be corrupt...
└ @ GeoIP ~/.julia/packages/GeoIP/ct0la/src/data.jl:96
ERROR: UndefVarError: blocks not defined
```

Browsing the source I found the `update` function:
```julia
julia> GeoIP.update()
┌ Error: Failed to download checksum file from MaxMind, check network connectivity
└ @ GeoIP ~/.julia/packages/GeoIP/ct0la/src/data.jl:37
ERROR: MethodError: no method matching dldata(::Nothing)
```

**Comment by fredrikekre** [comment]
I guess the URLs are wrong?
```
$ curl -LI http://geolite.maxmind.com/download/geoip/database/GeoLite2-City-CSV.zip.md5
curl: (6) Could not resolve host: geolite.maxmind.com
```

**Comment by Arkoniak** [comment]
Yes, this method should be removed.

In 2019 IIRC, MaxMind removed direct access to its databases. Now you have to make an account and you should use their own downloaders to get the data (or you can download it via the web, after the login). It can be solved on Julia's side, but I do not think it's worth it. 

Another alternative is https://db-ip.com/db/ but it also requires account.

So, my current opinion is that data files should be downloaded separately, and GeoIP.jl should only provide a convenient wrapper to work with them. We can't even distribute these files with the repository, since they have special non-mit license.

**Comment by fredrikekre** [comment]
I see, perhaps that should be put in the readme.

**Comment by fredrikekre** [comment]
Closing in favor of #48.
